---
- name: Copy weave-kube-1.6.yaml
  copy:
    src: "{{ role_path }}/files/weave-kube-1.6.yaml"
    dest: ~/weave-kube-1.6.yaml

- name: Install weavenet
  command: kubectl apply -f weave-kube-1.6.yaml
