apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
api:
  advertiseAddress: {{ api_address }}
etcd:
  endpoints:
  - https://{{ first_master_ip }}:2379
  - https://{{ second_master_ip }}:2379
  - https://{{ third_master_ip }}:2379
  caFile: /etc/etcd/ca.pem
  certFile: /etc/etcd/kubernetes.pem
  keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: {{ cluster_subnet }}
apiServerCertSANs:
- {{ first_master_ip }}
- {{ second_master_ip }}
- {{ third_master_ip }}
apiServerExtraArgs:
  apiserver-count: "3"
controllerManagerExtraArgs:
  node-monitor-period: "2s"
  node-monitor-grace-period: "16s"
  pod-eviction-timeout: "30s"
