---
- name: Add an Apt signing key
  apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
- name: Install apt-transport-https
  apt:
        name: apt-transport-https
        state: present
- name: Add repository
  apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
- name: Install Docker
  apt:
        name: docker-ce=17.03.2~ce-0~ubuntu-xenial
        state: present
        update_cache: yes
