apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
api:
  advertiseAddress: {{ api_address }}
etcd:
  external:
    endpoints:
{% for host in groups['masters'] %}
    - https://{{ hostvars[host].ansible_host }}:2379
{% endfor %}
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
apiServerCertSANs:
- {{ api_address }}
{% for host in groups['masters'] %}
- {{ hostvars[host].ansible_host }}
{% endfor %}
apiServerExtraArgs:
  apiserver-count: "3"
controllerManagerExtraArgs:
  node-monitor-period: "2s"
  node-monitor-grace-period: "16s"
  pod-eviction-timeout: "30s"
